package io.kyberorg.yalsee.exception;

import io.kyberorg.yalsee.ui.err.ServerErrorLoopView;

/**
 * Exception, which not intended to be thrown, just {@link ServerErrorLoopView} handles it.
 *
 * @since 2.7.4
 */
public class NeedForLoopException extends YalsException {
}
